#name: Build
#on: [ push ]
#
#jobs:
#  build_on_win:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@master
#        with:
#          node-version: 14
#      - name: get versions
#        run: npm version
#      - name: install dependencies
#        run: npm ci
#      - name: build
#        run: npm run make
